# Generated by Django 4.0.5 on 2022-06-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='card',
        ),
    ]
